# Generated by Django 4.2.7 on 2023-11-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_deletedestimates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitems',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='user',
        ),
        migrations.DeleteModel(
            name='estimate_comments',
        ),
        migrations.DeleteModel(
            name='EstimateItems',
        ),
        migrations.DeleteModel(
            name='Estimates',
        ),
    ]
