# Generated by Django 4.2.7 on 2023-11-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_estimates_estimateitems_estimate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitems',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='company',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='estimates',
            name='user',
        ),
        migrations.DeleteModel(
            name='estimate_comments',
        ),
        migrations.DeleteModel(
            name='EstimateItems',
        ),
        migrations.DeleteModel(
            name='Estimates',
        ),
    ]
