# Generated by Django 4.2.7 on 2023-11-18 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0007_remove_recurring_invoice_cust_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurring_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255, null=True)),
                ('cemail', models.CharField(max_length=255, null=True)),
                ('cadrs', models.CharField(max_length=255, null=True)),
                ('gsttr', models.CharField(max_length=255, null=True)),
                ('gstnum', models.CharField(max_length=255, null=True)),
                ('p_supply', models.CharField(max_length=255)),
                ('entry_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('reinvoiceno', models.CharField(max_length=255, null=True)),
                ('order_num', models.CharField(max_length=255)),
                ('every', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('terms', models.CharField(max_length=255)),
                ('cust_note', models.TextField()),
                ('conditions', models.TextField()),
                ('attachment', models.ImageField(null=True, upload_to='image/')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('shipping_charge', models.FloatField(blank=True, null=True)),
                ('adjustment', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('estimate', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recur_itemtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=255)),
                ('hsncode', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('amt', models.FloatField(blank=True, null=True)),
                ('ri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.recurring_invoice')),
            ],
        ),
    ]
