# Generated by Django 4.2.7 on 2023-11-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_estimates_estimateitems_estimate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='AttachE',
        ),
        migrations.DeleteModel(
            name='ExpenseE',
        ),
    ]
