# Generated by Django 4.2.7 on 2023-11-24 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0013_remove_expensee_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, max_length=255, null=True)),
                ('expense_type', models.TextField(blank=True, max_length=255, null=True)),
                ('paid', models.TextField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('hsn_code', models.TextField(blank=True, max_length=255, null=True)),
                ('gst_treatment', models.TextField(blank=True, max_length=255, null=True)),
                ('gstin', models.TextField(blank=True, max_length=255, null=True)),
                ('destination_of_supply', models.TextField(blank=True, max_length=255, null=True)),
                ('reverse_charge', models.TextField(blank=True, max_length=255, null=True)),
                ('tax', models.TextField(blank=True, max_length=255, null=True)),
                ('invoice', models.TextField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_tags', models.TextField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sac', models.TextField(blank=True, max_length=255, null=True)),
                ('taxamt', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='expense_image/')),
                ('status', models.TextField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.company_details')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table')),
            ],
        ),
        migrations.CreateModel(
            name='AttachE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.expensee')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
