# Generated by Django 4.2.7 on 2023-12-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0020_expensee_expense_comments_attache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_comments',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expense_comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='AttachE',
        ),
        migrations.DeleteModel(
            name='expense_comments',
        ),
        migrations.DeleteModel(
            name='ExpenseE',
        ),
    ]
